import { chromium } from 'playwright'
const browser = await chromium.launch({ args: ['--disable-web-security'] })
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } })
const page = await ctx.newPage()
page.on('console', m => console.log('[browser]', m.type(), m.text()))
page.on('pageerror', e => console.log('[pageerror]', e.message))
page.on('request', r => { if (r.url().includes('/api/')) console.log('[req]', r.method(), r.url()) })
page.on('response', r => { if (r.url().includes('/api/')) console.log('[res]', r.status(), r.url()) })
await page.goto('http://localhost:5173/login', { waitUntil: 'networkidle' })
await page.waitForTimeout(3000)
console.log('--- HTML SNIPPET ---')
const html = await page.content()
console.log(html.substring(0, 2500))
console.log('--- HAS EMAIL INPUT? ---')
console.log('count:', await page.locator('input[type="email"]').count())
await browser.close()
